export type Token<T> = symbol & { readonly __type?: T };

export const TOKENS = {
  HttpClient: Symbol.for('HttpClient'),
  SecureStorage: Symbol.for('SecureStorage'),
  AuthRepository: Symbol.for('AuthRepository'),
  RecipeRepository: Symbol.for('RecipeRepository'),
  TaxonomyRepository: Symbol.for('TaxonomyRepository'),
  LoadTaxonomyUseCase: Symbol.for('LoadTaxonomyUseCase'),
  RecipeDraftRepository: Symbol.for('RecipeDraftRepository'),
  FavoritesRepository: Symbol.for('FavoritesRepository'),
  AddFavoriteUseCase: Symbol.for('AddFavoriteUseCase'),
  RemoveFavoriteUseCase: Symbol.for('RemoveFavoriteUseCase'),
  LoadFavoritesUseCase: Symbol.for('LoadFavoritesUseCase'),
  HealthCheckService: Symbol.for('HealthCheckService'),
  CommentRepository: Symbol.for('CommentRepository'),
  LikeRepository: Symbol.for('LikeRepository'),
  LikeRecipeUseCase: Symbol.for('LikeRecipeUseCase'),
  UnlikeRecipeUseCase: Symbol.for('UnlikeRecipeUseCase'),
  NotificationRepository: Symbol.for('NotificationRepository'),
  UserProfileRepository: Symbol.for('UserProfileRepository'),
  ListNotificationsUseCase: Symbol.for('ListNotificationsUseCase'),
  MarkAllReadUseCase: Symbol.for('MarkAllReadUseCase'),
  RegisterDeviceTokenUseCase: Symbol.for('RegisterDeviceTokenUseCase'),
  GetUserProfileUseCase: Symbol.for('GetUserProfileUseCase'),
  FeedbackRepository: Symbol.for('FeedbackRepository'),
  SubmitFeedbackUseCase: Symbol.for('SubmitFeedbackUseCase'),
  KeyValueStore: Symbol.for('KeyValueStore'),
  NotificationService: Symbol.for('NotificationService'),
  AlarmAudioService: Symbol.for('AlarmAudioService'),
} as const;
